version: "3"
services: 
  data-tabble:
    image: node:latest
    container_name: data-table
    ports:
      - 8001:8001
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm i && npm run start"